pipeline {
    agent any
    stages {
        stage('Build') {
           
               agent{
                docker{
                    image 'composer:latest'
                    args '''
                    -v ./:/app
                    -w /app
                    '''

                    reuseNode true
                }
            }
             steps {
                    echo "building .... "
                    sh '''
                        composer install --no-interaction 
                        composer dump-autoload
                        composer dump-env prod
                     ''' 
            }
        }
        stage('Test') {
            steps {
                 echo "testing ... "
                 sh "ls -la"
            }
        }
        stage('Deploy') {
            steps {
                 echo "deploying ... "
            }
        }
    }
}