pipeline {
    agent any
      environment {
        // vist this https://www.jenkins.io/doc/book/pipeline/syntax/#environment
        REGISTRY_CREDS=credentials('dockerhub-mahdi-magroun')
    }
    stages {
        stage('Preparation') {
           
               agent{
                docker{
                    image 'composer:latest'
                    args """
                    -v ./:/app
                    -w /app
                    """
                    reuseNode true
                }
            }
             steps {
                    echo "Preparing code .... "
                    sh '''
                    env

                       composer install --ignore-platform-reqs --no-scripts
                 
                     ''' 
                     //        APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
            }
        }
        stage('Build') {
             
            steps {
                 echo "Building ... "
                
                 script {
                   if(env.BRANCH_NAME == 'main'){
                   sh """ docker build  --build-arg APP_ENV=prod \
                        --build-arg db_conn=${blog_db_url_prod} \
                     -t mahdi0188/symfony-blog:latest .
                     """


                   }
                   else{
                     sh """ docker build  --build-arg APP_ENV=prod \
                        --build-arg db_conn=${blog_db_url_dev} \
                     -t mahdi0188/symfony-blog:latest .
                     """

                   }

                 }
            }
        }
          stage('Testing') {
            agent{
              docker{
                    image 'mahdi0188/symfony-blog:latest'
                    args '''
                    -w /var/www/html/back-end
                    '''

                    reuseNode true
                }
            }
            steps {
                 echo "Testing ... "
                 // sh "php bin/phpunit":: need some investment 
                   
            }
        }
        stage('Database Migrations') {
            agent{
              docker{
                    image 'mahdi0188/symfony-blog:latest'
                    args '''
                    -w /var/www/html/back-end
                    '''

                    reuseNode true
                }
            }
            steps {
                 echo "Migrating ... "
                    echo "migrating .........................................................."
                    script {
                        
                        def migration = sh(script: "php bin/console doctrine:migrations:diff --no-interaction", returnStatus: true)
                        
                        if( migration == 0){
                          sh "php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration " 
                        }
                        else{
                           echo  "no migration to apply"
                           
                        }
                    }
                 
                 
              
                 

            }
        }
         stage('Pushing To Registry ') {
             
            steps {
                 echo "Pushing ... "
                  sh 'docker login -u $REGISTRY_CREDS_USR -p $REGISTRY_CREDS_PSW'
                  sh "docker push mahdi0188/symfony-blog-final:latest"
                   
            }
        }

        stage('Deploy Dev') {
            when {
                branch "develop"
            }
            steps {
                 echo "deploying into development envirement  ... "
               /**
               * connect to docker container 
               * 
               */
            }
        }

         stage('Deploy Prod') {
              when {
                branch "main"
            }
            steps {
                echo "deploying into production envirement  ... "
                 // here do not forget to lanch database migrations
            }
        }
    }
}