pipeline {
    agent any
      environment {
        // vist this https://www.jenkins.io/doc/book/pipeline/syntax/#environment
        REGISTRY_CREDS=credentials('dockerhub-mahdi-magroun')
    }
    stages {
        stage('Preparation') {
           
               agent{
                docker{
                    image 'composer:latest'
                    args '''
                    -v ./:/app
                    -w /app
                    '''

                    reuseNode true
                }
            }
             steps {
                    echo "Preparing code .... "
                    sh '''
                        composer install --no-interaction --no-dev --optimize-autoloader  
                 
                     ''' 
                     //        APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear
            }
        }
        stage('Build') {
             
            steps {
                 echo "Building ... "
                 sh "docker build -t mahdi0188/e-commerce:latest ."
                   
            }
        }
          stage('Testing') {
            agent{
              docker{
                    image 'mahdi0188/e-commerce:latest'
                    args '''
                    -w /var/www/html/back-end
                    '''

                    reuseNode true
                }
            }
            steps {
                 echo "Testing ... "
                 sh "./bin/phpunit"
                   
            }
        }
         stage('Pushing To Registry ') {
             
            steps {
                 echo "Pushing ... "
                  sh 'docker login -u $REGISTRY_CREDS_USR -p $REGISTRY_CREDS_PSW'
                  sh "docker push mahdi0188/spring-boot-docker:latest"
                   
            }
        }

        stage('Deploy Dev') {
            steps {
                 echo "deploying ... "
                 // here do not forget to lanch database migrations
            }
        }

         stage('Deploy Prod') {
            steps {
                 echo "deploying ... "
                 // here do not forget to lanch database migrations
            }
        }
    }
}